# Generated by Django 4.1.7 on 2023-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(to='Products.hashtag'),
        ),
    ]
